package cli

// SurfaceCases is every invocation the frozen table replays.
//
// The list lives in code and the captured answers live in
// testdata/golden/cli/cli.json, regenerated with:
//
//	go test ./internal/cli/ -run Frozen -update
//
// It moved here when the Ruby tree was deleted. Until then the fixture was
// captured FROM the Ruby and proved the port faithful; now it is captured from
// this binary and proves only that today's behavior matches yesterday's. That
// is a weaker claim, and -update is therefore a decision rather than a step in
// fixing a red test -- regenerating to make a failure go away is how a baseline
// quietly stops meaning anything.
//
// Only invocations that never reach a scheduler belong here, so the table stays
// hermetic and replayable on any machine. The live lifecycle is test/e2e's job.
var SurfaceCases = [][]string{
	{},
	{"help"},
	{"-h"},
	{"--help"},
	{"version"},
	{"--version"},
	{"log"},
	{"rm"},
	{"remove"},
	{"pause"},
	{"resume"},
	{"run"},
	{"log", "nosuch"},
	{"rm", "nosuch"},
	{"pause", "nosuch"},
	{"resume", "nosuch"},
	{"run", "nosuch"},
	{"log", "-n", "5", "nosuch"},
	{"log", "nosuch", "-n", "5"},
	{"log", "-n", "0", "nosuch"},
	{"log", "-n", "notanumber", "nosuch"},
	{"list"},
	{"ls"},
	{"list", "--json"},
	{"ls", "--json"},
	{"list", "--json", "extra"},
	{"frobnicate"},
	{"15m"},
	{"day", "9am"},
	{"15m", "--"},
	{"banana", "--", "true"},
	{"0m", "--", "true"},
	{"day", "13pm", "--", "true"},
	{"15m", "--name", "--", "true"},
	{"15m", "--name", "--quiet", "--", "true"},
	{"15m", "--name=", "--", "true"},
	{"15m", "--name", "...", "--", "true"},
	{"15m", "--name", ".", "--", "true"},
	{"15m", "--name", "..", "--", "true"},
	{"15m", "--timeout", "--", "true"},
	{"15m", "--timeout", "0s", "--", "true"},
	{"15m", "--timeout", "5x", "--", "true"},
	{"15m", "--timeout=0s", "--", "true"},
	{"15m", "--timeout", "notaduration", "--", "true"},
	{"15m", "--timeout", "5", "--", "true"},
	{"15m", "--timeout", "-5m", "--", "true"},
	{"15m", "--timeout", "0", "--", "true"},
	{"15m", "--name", "/", "--", "true"},
	{"15m", "--name", "//", "--", "true"},
	{"15m", "--name", "---", "--", "true"},
	{"15m", "--name", " ", "--", "true"},
	{"15m", "--name", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "--", "true"},
	{"--", "true"},
	{"0s", "--", "true"},
	{"9s", "--", "true"},
	{"1d", "--", "true"},
	{"25h99", "--", "true"},
	{"mon", "8am", "--", "true"},
	{"day", "5s", "--", "true"},
	{"day", "9am,", "--", "true"},
	{"day", ",", "--", "true"},
	{",monday", "10:00", "--", "true"},
	{"day", "9am", "6pm", "--", "true"},
	{"", "--", "true"},
	{"list", "--json"},
	{"--json", "list"},
	{"ls", "--json", "extra"},
	{"list", "extra"},
	{"ls"},
	{"log", "-n", "1", "nosuch"},
	{"log", "nosuch", "-n", "1"},
	{"log", "-n", "-1", "nosuch"},
	{"log", "-n", "999999", "nosuch"},
	{"log", "-n", "nosuch"},
	{"version", "extra"},
	{"help", "extra"},
	{"rm", "nosuch", "extra"},
	{"pause", "nosuch", "extra"},
	{"--nonsense"},
	{"-x"},
	{"--json"},

	// 0.5.0 additions. Every one of these was a usage error before the verb
	// existed, so their old answers are in the fixture too -- the table records
	// the change rather than hiding it.
	{"inspect"},
	{"inspect", "nosuch"},
	{"inspect", "nosuch", "--json"},
	{"exists"},
	{"exists", "nosuch"},
	{"set"},
	{"set", "15m"},
	{"set", "15m", "--", "true"},
	{"set", "banana", "--name", "x", "--", "true"},
	{"set", "15m", "--name", "", "--", "true"},
	{"schema"},
	{"schema", "list"},
	{"schema", "inspect"},
	{"schema", "error"},
	{"schema", "nosuch"},
	{"version", "--json"},
	{"list", "--json"},
	{"log", "nosuch", "--json"},
	{"rm", "nosuch", "--json"},
	{"pause", "nosuch", "--json"},
	{"resume", "nosuch", "--json"},
	{"run", "nosuch", "--json"},
	{"run", "nosuch", "--dry-run"},
	{"doctor", "--json"},
	{"banana", "--", "true"},
	{"15m", "--timeout", "0s", "--json", "--", "true"},
}
